[project]
name = "psych_723"
version = "0.1.0"
requires-python = ">=3.12,<3.13"
dependencies = [
    "ipykernel>=7.1.0",
    "ipywidgets>=8.1.8",
    "matplotlib>=3.10.8",
    "nbgrader>=0.9.5",
    "numpy==2.0.2",
    "pandas==2.2.2",
]
